config/routes.rb
Rails.application.routes.draw do
  resources :indicadors
  resources :tipus_indicadors
  resources :tipus_dada_inventaris
  resources :producte_dapcons
  resources :cerca_productes
  get 'productes/cerca_productes'
  get 'dapcons', to: 'dapcons#index', :as => :dapcons
  get 'dapcons/que_son'
  get 'dapcons/utilitat'
  get 'dapcons/organitzacions_afiliades'
  get 'dapcons/productes_registrats'
  get 'dapcons/empreses_dapcons'
  get 'dapcons/documents_oficials'
  get 'dapcons/administradors'
  get 'dapcons/consell_assessor'
  get 'dapcons/panells_sectorials'
  get 'dapcons/eco_platform'
  get 'dapcons/entitats_colaboradores'
  get 'dapcons/verificadors'
  get 'dapcons/afiliacio'
  get 'dapcons/registrar_producte'
  get 'dapcons/contacte'
  get 'dapcons/comparador'
  resources :foto_casos
  resources :photos
  get 'temes_clau/index'
  get 'temes_clau/marc_conceptual'
  get 'temes_clau/materials'
  get 'temes_clau/energia_passius'
  get 'temes_clau/energia_actius'
  get 'temes_clau/energia_renovables'
  get 'temes_clau/aigua'
  get 'temes_clau/residus'
  get 'temes_clau/salut'
  get 'videos/llistat'
  get 'cas_practics/llistat'
  get 'productes/llistat'

  resources :videos
  resources :productes
  resources :cas_practics
  resources :noticies
  devise_for :users
  get 'home/index'
  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :update, Noticia do |noticia|
        noticia.user == user
      end
      can :destroy, Noticia do |noticia|
        noticia.user == user
      end
      can :create, Noticia
      can :read, :all
    end  
  end
end

app/models/cas_practic.rb
class CasPractic < ApplicationRecord

	has_many :foto_casos

end

app/models/cerca_producte.rb
class CercaProducte < ApplicationRecord
end

app/models/foto_cas.rb
class FotoCas < ApplicationRecord
	include ImageUploader[:image]

	belongs_to :cas_practic
end

app/models/image_uploader.rb
class ImageUploader < Shrine
	require "image_processing/mini_magick"
	include ImageProcessing::MiniMagick
  plugin :processing
  plugin :versions

	Attacher.validate do
    validate_max_size 2.megabyte, message: "is too large (max is 2 MB)"
    validate_mime_type_inclusion ['image/jpg', 'image/jpeg', 'image/png']
	end

	plugin :determine_mime_type
	plugin :cached_attachment_data
	plugin :remove_attachment
	plugin :delete_raw
	plugin :store_dimensions

	process(:store) do |io, context|
    { original: io, medium: resize_to_fit!(io.download, 600, 600), thumb: resize_to_limit!(io.download, 300, 300) }
  end
end

app/models/indicador.rb
class Indicador < ApplicationRecord

	belongs_to :producte_dapcons

end

app/models/noticia.rb
class Noticia < ApplicationRecord

	include ImageUploader::Attachment.new(:image)

end

app/models/photo.rb
class Photo < ApplicationRecord
	include ImageUploader[:image]
end

app/models/producte.rb
class Producte < ApplicationRecord
end

app/models/producte_dapcons.rb
class ProducteDapcons < ApplicationRecord

	has_many :indicadors

end

app/models/tipus_indicador.rb
class TipusIndicador < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    [first_name, last_name].compact.join(' ')
  end

end

app/models/video.rb
class Video < ApplicationRecord

	include ImageUploader::Attachment.new(:image)
	
end

app/controllers/cas_practics_controller.rb
class CasPracticsController < ApplicationController
  before_action :set_cas_practic, only: [:show, :edit, :update, :destroy]

  def llistat
    @cas_practics = CasPractic.all
  end
  # GET /cas_practics
  # GET /cas_practics.json
  def index
    @cas_practics = CasPractic.all.order(created_at: :desc)
  end

  # GET /cas_practics/1
  # GET /cas_practics/1.json
  def show
    @fotos_cas = FotoCas.where(cas_practic_id: 1)
  end

  # GET /cas_practics/new
  def new
    @cas_practic = CasPractic.new
  end

  # GET /cas_practics/1/edit
  def edit
  end

  # POST /cas_practics
  # POST /cas_practics.json
  def create
    @cas_practic = CasPractic.new(cas_practic_params)

    respond_to do |format|
      if @cas_practic.save
        format.html { redirect_to @cas_practic, notice: 'Cas practic was successfully created.' }
        format.json { render :show, status: :created, location: @cas_practic }
      else
        format.html { render :new }
        format.json { render json: @cas_practic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cas_practics/1
  # PATCH/PUT /cas_practics/1.json
  def update
    respond_to do |format|
      if @cas_practic.update(cas_practic_params)
        format.html { redirect_to @cas_practic, notice: 'Cas practic was successfully updated.' }
        format.json { render :show, status: :ok, location: @cas_practic }
      else
        format.html { render :edit }
        format.json { render json: @cas_practic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cas_practics/1
  # DELETE /cas_practics/1.json
  def destroy
    @cas_practic.destroy
    respond_to do |format|
      format.html { redirect_to cas_practics_url, notice: 'Cas practic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cas_practic
      @cas_practic = CasPractic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cas_practic_params
      params.require(:cas_practic).permit(:titol_ca, :resum_ca, :permalink_ca, :descripcio_ca, :emplacament_ca, :arquitectura_ca, :materials_ca, :energia_ca, :aigua_ca, :certificacions_ca, :arquitectes_ca, :emplacament_ca, :any_construccio_ca, :us_edifici_ca, :tipus_promocio_ca, :titol_es, :resum_es, :permalink_es, :descripcio_es, :emplacament_es, :arquitectura_es, :materials_es, :energia_es, :aigua_es, :certificacions_es, :arquitectes_es, :emplacament_es, :any_construccio_es, :us_edifici_es, :tipus_promocio_es)
    end
end

app/helpers/cas_practics_helper.rb
module CasPracticsHelper
end

app/helpers/dapcons_helper.rb
module DapconsHelper
end

app/helpers/foto_casos_helper.rb
module FotoCasosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/indicadors_helper.rb
module IndicadorsHelper
end

app/helpers/noticies_helper.rb
module NoticiesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/productes_helper.rb
module ProductesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/cas_practics/_form.html.erb
<%= simple_form_for(@cas_practic) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :titol_ca %>
    <%= f.input :resum_ca %>
    <%= f.input :permalink_ca %>
    <%= f.input :descripcio_ca, as: :hidden %>
    <trix-editor input="cas_practic_descripcio_ca"></trix-editor>
    <%= f.input :emplacament_ca %>
    <%= f.input :arquitectura_ca %>
    <%= f.input :materials_ca %>
    <%= f.input :energia_ca %>
    <%= f.input :aigua_ca %>
    <%= f.input :certificacions_ca %>
    <%= f.input :arquitectes_ca %>
    <%= f.input :emplacament_ca %>
    <%= f.input :any_construccio_ca %>
    <%= f.input :us_edifici_ca %>
    <%= f.input :tipus_promocio_ca %>
    <%= f.input :titol_es %>
    <%= f.input :resum_es %>
    <%= f.input :permalink_es %>
    <%= f.input :descripcio_es %>
    <%= f.input :emplacament_es %>
    <%= f.input :arquitectura_es %>
    <%= f.input :materials_es %>
    <%= f.input :energia_es %>
    <%= f.input :aigua_es %>
    <%= f.input :certificacions_es %>
    <%= f.input :arquitectes_es %>
    <%= f.input :emplacament_es %>
    <%= f.input :any_construccio_es %>
    <%= f.input :us_edifici_es %>
    <%= f.input :tipus_promocio_es %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cas_practics/edit.html.erb
<h1>Editing Cas Practic</h1>

<%= render 'form', cas_practic: @cas_practic %>

<%= link_to 'Show', @cas_practic %> |
<%= link_to 'Back', cas_practics_path %>

app/views/cas_practics/index.html.erb
<div class="container">
  <div class="grid-x">
    <div class="medium-12 cell">
      <div class="main-title-container">
        <span class="main-title"><%= t('.casos_practics') %></span>
      </div>
    </div>
  </div>

  <% counter = 0 %>
  <div class="cas-array-container">
    <div class="grid-x grid-margin-x">
      <% @cas_practics.each do |cas| %>
        <% if counter != 0 && counter % 3 == 0 %>
          </div>
          <div class="grid-x grid-margin-x">
        <% end %>

        <div class="medium-4 cell">
          <div class="index-cas-container">
            <div class="img-index-cas">
              <%= link_to cas do %>
                
              <% end %>  
            </div>
            <div class="text-index-cas">
              <%= link_to cas do %>
                <h4><%= cas.titol_ca %></h4>
                <p class="resum-video"><%= sanitize cas.descripcio_ca %></p>
              <% end %>
            </div>
          </div>
        </div>
        <% counter += 1 %>
      <% end %>
    </div>
  </div>
</div>

app/views/cas_practics/llistat.html.erb
<p id="notice"><%= notice %></p>

<h1>Cas Practics</h1>

<table>
  <thead>
    <tr>
      <th>Titol ca</th>
      <th>Resum ca</th>
      <th>Permalink ca</th>
      <th>Descripcio ca</th>
      <th>Emplacament ca</th>
      <th>Arquitectura ca</th>
      <th>Materials ca</th>
      <th>Energia ca</th>
      <th>Aigua ca</th>
      <th>Certificacions ca</th>
      <th>Arquitectes ca</th>
      <th>Emplacament ca</th>
      <th>Any construccio ca</th>
      <th>Us edifici ca</th>
      <th>Tipus promocio ca</th>
      <th>Titol es</th>
      <th>Resum es</th>
      <th>Permalink es</th>
      <th>Descripcio es</th>
      <th>Emplacament es</th>
      <th>Arquitectura es</th>
      <th>Materials es</th>
      <th>Energia es</th>
      <th>Aigua es</th>
      <th>Certificacions es</th>
      <th>Arquitectes es</th>
      <th>Emplacament es</th>
      <th>Any construccio es</th>
      <th>Us edifici es</th>
      <th>Tipus promocio es</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cas_practics.each do |cas_practic| %>
      <tr>
        <td><%= cas_practic.titol_ca %></td>
        <td><%= cas_practic.resum_ca %></td>
        <td><%= cas_practic.permalink_ca %></td>
        <td><%= cas_practic.descripcio_ca %></td>
        <td><%= cas_practic.emplacament_ca %></td>
        <td><%= cas_practic.arquitectura_ca %></td>
        <td><%= cas_practic.materials_ca %></td>
        <td><%= cas_practic.energia_ca %></td>
        <td><%= cas_practic.aigua_ca %></td>
        <td><%= cas_practic.certificacions_ca %></td>
        <td><%= cas_practic.arquitectes_ca %></td>
        <td><%= cas_practic.emplacament_ca %></td>
        <td><%= cas_practic.any_construccio_ca %></td>
        <td><%= cas_practic.us_edifici_ca %></td>
        <td><%= cas_practic.tipus_promocio_ca %></td>
        <td><%= cas_practic.titol_es %></td>
        <td><%= cas_practic.resum_es %></td>
        <td><%= cas_practic.permalink_es %></td>
        <td><%= cas_practic.descripcio_es %></td>
        <td><%= cas_practic.emplacament_es %></td>
        <td><%= cas_practic.arquitectura_es %></td>
        <td><%= cas_practic.materials_es %></td>
        <td><%= cas_practic.energia_es %></td>
        <td><%= cas_practic.aigua_es %></td>
        <td><%= cas_practic.certificacions_es %></td>
        <td><%= cas_practic.arquitectes_es %></td>
        <td><%= cas_practic.emplacament_es %></td>
        <td><%= cas_practic.any_construccio_es %></td>
        <td><%= cas_practic.us_edifici_es %></td>
        <td><%= cas_practic.tipus_promocio_es %></td>
        <td><%= link_to 'Show', cas_practic %></td>
        <td><%= link_to 'Edit', edit_cas_practic_path(cas_practic) %></td>
        <td><%= link_to 'Destroy', cas_practic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cas Practic', new_cas_practic_path %>

app/views/cas_practics/new.html.erb
<h1>New Cas Practic</h1>

<%= render 'form', cas_practic: @cas_practic %>

<%= link_to 'Back', cas_practics_path %>

app/views/cas_practics/show.html.erb
<div class="container container-show-cas">
  <div class="grid-x grid-margin-x">
    <div class="medium-12 cell">
      <div class="titol-cas">
        <%= @cas_practic.titol_ca %>
      </div>
    </div>
  </div>
  <div class="grid-x grid-margin-x">
    <div class="medium-8 cell">
      <div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit data-use-m-u-i="false">
        <div class="orbit-wrapper">
          <div class="orbit-controls">
            <button class="orbit-previous"><span class="show-for-sr">Previous Slide</span>&#9664;&#xFE0E;</button>
            <button class="orbit-next"><span class="show-for-sr">Next Slide</span>&#9654;&#xFE0E;</button>
          </div>
          <ul class="orbit-container">
            <% @fotos_cas.each do |foto| %>
              <li class="is-active orbit-slide">
                <figure class="orbit-figure">
                  
                  <%= image_tag foto.image_url(:original, public: true, host: "https://d2dvjaugh07t30.cloudfront.net"), class: 'orbit-image' %>
                  <figcaption class="orbit-caption"><%= foto.text_ca %></figcaption>
                </figure>
              </li>
            <% end %>
          </ul>
        </div>
        <nav class="orbit-bullets">
          
          <button class="is-active" data-slide="0"><span class="show-for-sr">First slide details.</span><span class="show-for-sr">Current Slide</span></button>
          <button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>
          <button data-slide="2"><span class="show-for-sr">Third slide details.</span></button>
          
        </nav>
      </div>


      <% if params[:locale] == 'ca' %>
        <div class="text-cas">
          <%= sanitize @cas_practic.descripcio_ca %>
        </div>
      <% end %>
    </div>
    <div class="medium-4 cell">
      <div class="titol-seccio">
        DADES DE L'EDIFICI
      </div>
      <div class="credits-cas">
        <p><span class="titol-credits-cas">Arquitectes:</span><br/>
        <%= @cas_practic.arquitectes_ca %></p>
        <p><span class="titol-credits-cas">Emplaçament:</span><br/>
        <%= @cas_practic.emplacament_ca %></p>
        <p><span class="titol-credits-cas">Any de construcció:</span><br/>
        <%= @cas_practic.any_construccio_ca %></p>
        <p><span class="titol-credits-cas">Ús de l'edifici:</span><br/>
        <%= @cas_practic.us_edifici_ca %></p>
        <p><span class="titol-credits-cas">Tipus de promoció:</span><br/>
        <%= @cas_practic.tipus_promocio_ca %></p>
      </div>

      <div class="titol-seccio">
        NOTÍCIES
      </div>

    </div>
  </div>
</div>