config/routes.rb
Rails.application.routes.draw do
  resources :indicadors
  resources :tipus_indicadors
  resources :tipus_dada_inventaris
  resources :producte_dapcons
  resources :cerca_productes
  get 'productes/cerca_productes'
  get 'dapcons', to: 'dapcons#index', :as => :dapcons
  get 'dapcons/que_son'
  get 'dapcons/utilitat'
  get 'dapcons/organitzacions_afiliades'
  get 'dapcons/productes_registrats'
  get 'dapcons/empreses_dapcons'
  get 'dapcons/documents_oficials'
  get 'dapcons/administradors'
  get 'dapcons/consell_assessor'
  get 'dapcons/panells_sectorials'
  get 'dapcons/eco_platform'
  get 'dapcons/entitats_colaboradores'
  get 'dapcons/verificadors'
  get 'dapcons/afiliacio'
  get 'dapcons/registrar_producte'
  get 'dapcons/contacte'
  get 'dapcons/comparador'
  resources :foto_casos
  resources :photos
  get 'temes_clau/index'
  get 'temes_clau/marc_conceptual'
  get 'temes_clau/materials'
  get 'temes_clau/energia_passius'
  get 'temes_clau/energia_actius'
  get 'temes_clau/energia_renovables'
  get 'temes_clau/aigua'
  get 'temes_clau/residus'
  get 'temes_clau/salut'
  get 'videos/llistat'
  get 'cas_practics/llistat'
  get 'productes/llistat'

  resources :videos
  resources :productes
  resources :cas_practics
  resources :noticies
  devise_for :users
  get 'home/index'
  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :update, Noticia do |noticia|
        noticia.user == user
      end
      can :destroy, Noticia do |noticia|
        noticia.user == user
      end
      can :create, Noticia
      can :read, :all
    end  
  end
end

app/models/cas_practic.rb
class CasPractic < ApplicationRecord

	has_many :foto_casos

end

app/models/cerca_producte.rb
class CercaProducte < ApplicationRecord
end

app/models/foto_cas.rb
class FotoCas < ApplicationRecord
	include ImageUploader[:image]

	belongs_to :cas_practic
end

app/models/image_uploader.rb
class ImageUploader < Shrine
	require "image_processing/mini_magick"
	include ImageProcessing::MiniMagick
  plugin :processing
  plugin :versions

	Attacher.validate do
    validate_max_size 2.megabyte, message: "is too large (max is 2 MB)"
    validate_mime_type_inclusion ['image/jpg', 'image/jpeg', 'image/png']
	end

	plugin :determine_mime_type
	plugin :cached_attachment_data
	plugin :remove_attachment
	plugin :delete_raw
	plugin :store_dimensions

	process(:store) do |io, context|
    { original: io, medium: resize_to_fit!(io.download, 600, 600), thumb: resize_to_limit!(io.download, 300, 300) }
  end
end

app/models/indicador.rb
class Indicador < ApplicationRecord

	belongs_to :producte_dapcons

end

app/models/noticia.rb
class Noticia < ApplicationRecord

	include ImageUploader::Attachment.new(:image)

end

app/models/photo.rb
class Photo < ApplicationRecord
	include ImageUploader[:image]
end

app/models/producte.rb
class Producte < ApplicationRecord
end

app/models/producte_dapcons.rb
class ProducteDapcons < ApplicationRecord

	has_many :indicadors

end

app/models/tipus_indicador.rb
class TipusIndicador < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    [first_name, last_name].compact.join(' ')
  end

end

app/models/video.rb
class Video < ApplicationRecord

	include ImageUploader::Attachment.new(:image)
	
end

app/controllers/temes_clau_controller.rb
class TemesClauController < ApplicationController
  def index
  end
end

app/helpers/dapcons_helper.rb
module DapconsHelper
end

app/helpers/foto_casos_helper.rb
module FotoCasosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/noticies_helper.rb
module NoticiesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/productes_helper.rb
module ProductesHelper
end

app/helpers/temes_clau_helper.rb
module TemesClauHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/temes_clau/index.html.erb
<% if params[:locale] == 'ca' %>
<div class="container">
	<div class="grid-x">
		<div class="medium-12 cell">
			<div class="main-title-container">
				<span class="main-title"><%= t('.temes_clau') %></span>
			</div>
		</div>
	</div>

	<div class="grid-x grid-margin-x grid-margin-y">

		<div class="medium-4 cell">
			<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/marc_conceptual_petit_ca.jpg', class: 'responsive-img'), temes_clau_marc_conceptual_path, alt: "Marc conceptual" %>	
		</div>
		<div class="medium-4 cell">
			<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/materials_petit_ca.jpg', class: 'responsive-img'), temes_clau_materials_path, alt: "Materials" %>	
		</div>
		<div class="medium-4 cell">
		<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/passius_petit_ca.jpg', class: 'responsive-img'), temes_clau_energia_passius_path, alt: "Energia: sistemes passius" %>
		</div>
	
	
		<div class="medium-4 cell">
			<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/actius_petit_ca.jpg', class: 'responsive-img'), temes_clau_energia_actius_path, alt: "Energia: sistemes actius" %>
		</div>
		<div class="medium-4 cell">
			<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/renovables_petit_ca.jpg', class: 'responsive-img'), temes_clau_energia_renovables_path, alt: "Energia: renovables" %>
		</div>
		<div class="medium-4 cell">
			<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/aigua_petit_ca.jpg', class: 'responsive-img'), temes_clau_aigua_path, alt: "Aigua" %>
		</div>
	
		<div class="medium-4 cell">
			<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/residus_petit_ca.jpg', class: 'responsive-img'), temes_clau_residus_path, alt: "Residus" %>
		</div>
		<div class="medium-4 cell">
			<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/salut_petit_ca.jpg', class: 'responsive-img'), temes_clau_salut_path, alt: "Salut" %>
		</div>
	</div>
</div>

<% else %>
<div class="container">
	<div class="grid-x">
		<div class="medium-12 cell">
			<div class="main-title-container">
				<span class="main-title"><%= t('.temes_clau') %></span>
			</div>
		</div>
	</div>

	<div class="grid-x grid-margin-x grid-margin-y">

		<div class="medium-4 cell">
			<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/marc_conceptual_petit_es.jpg'), temes_clau_marc_conceptual_path, alt: "Marco conceptual", class: "responsive-img" %>	
		</div>
		<div class="medium-4 cell">
			<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/materials_petit_es.jpg'), temes_clau_materials_path, alt: "Materiales", class: "responsive-img" %>	
		</div>
		<div class="medium-4 cell">
			<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/passius_petit_es.jpg'), temes_clau_energia_passius_path, alt: "Energía: sistemas pasivos", class: "responsive-img" %>
		</div>
	
	
		<div class="medium-4 cell">
			<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/actius_petit_es.jpg'), temes_clau_energia_actius_path, alt: "Energía: sistemas activos", class: "responsive-img" %>
		</div>
		<div class="medium-4 cell">
			<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/renovables_petit_es.jpg'), temes_clau_energia_renovables_path, alt: "Energía: renovables", class: "responsive-img" %>
		</div>
		<div class="medium-4 cell">
			<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/aigua_petit_es.jpg'), temes_clau_aigua_path, alt: "Agua", class: "responsive-img" %>
		</div>
	
		<div class="medium-4 cell">
			<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/residus_petit_es.jpg'), temes_clau_residus_path, alt: "Residuos", class: "responsive-img" %>
		</div>
		<div class="medium-4 cell">
			<%= link_to image_tag('https://s3-eu-west-1.amazonaws.com/csostenible/imatges/temes_clau/salut_petit_es.jpg'), temes_clau_salut_path, alt: "Salud", class: "responsive-img" %>
		</div>
	</div>
</div>

<% end %>

app/views/temes_clau/residus.html.erb
<% if params[:locale] == 'ca' %>
<div class="container">

	<div class="grid-x">
		<div class="medium-8 medium-offset-2 cell">
			<div class="paragraf-tema-clau">
				
				<div class="card blue lighten-4">
					<div class="card-content">
				  	<strong>Atenció!</strong> Estem treballant en l'actualització d'aquest tema clau.
				  </div>
				</div>

				<h2>Residus</h2>
				<p style="text-align: justify">Els residus de construcció i demolició (RCDs), procedeixen en la seva major part d'enderrocaments d'edificis i de les restes dels materials de construcció de les obres de nova planta i de petites obres de reformes en habitatges o urbanitzacions. Conforme a la legislació espanyola marc de residus -Llei 10/1998, de Residus- la competència sobre la seva gestió correspon a les Comunitats Autònomes, llevat dels procedents d'obres menors domiciliàries, que està confiada als ajuntaments. La major part dels RCDs es poden considerar inerts o assimilables a inerts, i per tant el seu poder contaminant és relativament baix però, per contra, el seu impacte visual és amb freqüència alt pel gran volum que ocupen i per l'escàs control ambiental exercit sobre els terrenys que es trien per al seu dipòsit.</p>
<p style="text-align: justify">Un segon impacte ambiental negatiu es deriva del balafiament de matèries primeres que implica el tipus de gestió que habitualment es fa a Espanya, que majoritàriament no contempla el reciclatge.</p>
<p style="text-align: justify">Els comunment denominats residus inerts poden tenir diferents procedències: els generats en les demolicions d'edificis, les excavacions de sòls o execució d'obres de reforma en carrers; els originats en carreteres i infraestructures; les excavacions d'obres d'edificació; les barreges dels enderrocs de construcció i els rebutjos o trencaments de la fabricació de peces i elements de construcció.</p>
<p style="text-align: justify">La majoria d'aquests residus inerts serien reutilitzables, generalment en altres usos en el mateix sector de la construcció, amb operacions de neteja i preparació prèvies no molt complicades, però la realitat actualment en el nostre país és que la majoria es destinen als abocadors (mes o menys controlats) i que els percentatges de reciclatge o reutilització de residus de construcció són dels mes baixos d'Europa.</p>

<p style="text-align: justify">En aquest article s'analitza quin és la situació actual de la gestió de residus de construcció en l'Estat Espanyol, el marc normatiu que la regeix, i es plantegen una sèrie d'estratègies de millora per a avançar cap a un escenari més sostenible.</p>
				
				
			</div>
		</div>
	</div>

</div>
<% else %>
<div class="container">

	<div class="grid-x">
		<div class="medium-8 medium-offset-2 cell">
			<div class="paragraf-tema-clau">
				
				<div class="card blue lighten-4">
					<div class="card-content">
				  	<strong>Atención!</strong> Estamos trabajando en la actualización de este tema clave.
				  </div>
				</div>

				<h2>Residuos</h2>

				<p style="padding-top: 7px;padding-right: 0px;padding-bottom: 7px;padding-left: 0px;text-align: justify;margin: 0px">Los residuos de construcción y demolición (RCDs), proceden en su mayor parte de derribos de edificios y de los restos de los materiales de construcción de las obras de nueva planta y de pequeñas obras de reformas en viviendas o urbanizaciones. Conforme a la legislación española marco de residuos -Ley 10/1998, de Residuos- la competencia sobre su gestión corresponde a las Comunidades Autónomas, excepto los procedentes de obras menores domiciliarias, que está confiada a los ayuntamientos. La mayor parte de los RCDs se pueden considerar inertes o asimilables a inertes, y por lo tanto su poder contaminante es relativamente bajo pero, por el contrario, su impacto visual es con frecuencia alto por el gran volumen que ocupan y por el escaso control ambiental ejercido sobre los terrenos sobre los que se realiza su vertido.</p>
<p style="padding-top: 7px;padding-right: 0px;padding-bottom: 7px;padding-left: 0px;text-align: justify;margin: 0px">Un segundo impacto ambiental negativo se deriva del despilfarro de materias primeras que implica el tipo de gestión que habitualmente se hace en España, que mayoritariamente no contempla el reciclaje. Los comúnmente denominados residuos inertes pueden tener diferentes procedencias: los generados en las demoliciones de edificios, las excavaciones de suelos o ejecución de obras de reforma en calles; los originados en carreteras e infraestructuras; las excavaciones de obras de edificación; las mezclas de los escombros de construcción y los rechazos o roturas de la fabricación de piezas y elementos de construcción. La mayoría de estos residuos inertes serían reutilizables, generalmente, en otros usos en el mismo sector de la construcción, con operaciones de limpieza y preparación previas no muy complicadas, pero la realidad actualmente en nuestro país es que la mayoría se destinan a los vertederos (más o menos controlados) y que los porcentajes de reciclaje o reutilización de residuos de construcción son de los más bajos de Europa.</p>

<p style="padding-top: 7px;padding-right: 0px;padding-bottom: 7px;padding-left: 0px;text-align: justify;margin: 0px">En este artículo se analiza cuál es la situación actual de la gestión de residuos de construcción en el Estado Español, el marco normativo que la rige, y se plantean una serie de estrategias de mejora para adelantar hacia un escenario más sostenible.</p>

			</div>
		</div>
	</div>

</div>
<% end %>