config/routes.rb
Rails.application.routes.draw do
  resources :indicadors
  resources :tipus_indicadors
  resources :tipus_dada_inventaris
  resources :producte_dapcons
  resources :cerca_productes
  get 'productes/cerca_productes'
  get 'dapcons', to: 'dapcons#index', :as => :dapcons
  get 'dapcons/que_son'
  get 'dapcons/utilitat'
  get 'dapcons/organitzacions_afiliades'
  get 'dapcons/productes_registrats'
  get 'dapcons/empreses_dapcons'
  get 'dapcons/documents_oficials'
  get 'dapcons/administradors'
  get 'dapcons/consell_assessor'
  get 'dapcons/panells_sectorials'
  get 'dapcons/eco_platform'
  get 'dapcons/entitats_colaboradores'
  get 'dapcons/verificadors'
  get 'dapcons/afiliacio'
  get 'dapcons/registrar_producte'
  get 'dapcons/contacte'
  get 'dapcons/comparador'
  resources :foto_casos
  resources :photos
  get 'temes_clau/index'
  get 'temes_clau/marc_conceptual'
  get 'temes_clau/materials'
  get 'temes_clau/energia_passius'
  get 'temes_clau/energia_actius'
  get 'temes_clau/energia_renovables'
  get 'temes_clau/aigua'
  get 'temes_clau/residus'
  get 'temes_clau/salut'
  get 'videos/llistat'
  get 'cas_practics/llistat'
  get 'productes/llistat'

  resources :videos
  resources :productes
  resources :cas_practics
  resources :noticies
  devise_for :users
  get 'home/index'
  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :update, Noticia do |noticia|
        noticia.user == user
      end
      can :destroy, Noticia do |noticia|
        noticia.user == user
      end
      can :create, Noticia
      can :read, :all
    end  
  end
end

app/models/cas_practic.rb
class CasPractic < ApplicationRecord

	has_many :foto_casos

end

app/models/cerca_producte.rb
class CercaProducte < ApplicationRecord
end

app/models/foto_cas.rb
class FotoCas < ApplicationRecord
	include ImageUploader[:image]

	belongs_to :cas_practic
end

app/models/image_uploader.rb
class ImageUploader < Shrine
	require "image_processing/mini_magick"
	include ImageProcessing::MiniMagick
  plugin :processing
  plugin :versions

	Attacher.validate do
    validate_max_size 2.megabyte, message: "is too large (max is 2 MB)"
    validate_mime_type_inclusion ['image/jpg', 'image/jpeg', 'image/png']
	end

	plugin :determine_mime_type
	plugin :cached_attachment_data
	plugin :remove_attachment
	plugin :delete_raw
	plugin :store_dimensions

	process(:store) do |io, context|
    { original: io, medium: resize_to_fit!(io.download, 600, 600), thumb: resize_to_limit!(io.download, 300, 300) }
  end
end

app/models/indicador.rb
class Indicador < ApplicationRecord

	belongs_to :producte_dapcons

end

app/models/noticia.rb
class Noticia < ApplicationRecord

	include ImageUploader::Attachment.new(:image)

end

app/models/photo.rb
class Photo < ApplicationRecord
	include ImageUploader[:image]
end

app/models/producte.rb
class Producte < ApplicationRecord
end

app/models/producte_dapcons.rb
class ProducteDapcons < ApplicationRecord

	has_many :indicadors

end

app/models/tipus_dada_inventari.rb
class TipusDadaInventari < ApplicationRecord
end

app/models/tipus_indicador.rb
class TipusIndicador < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    [first_name, last_name].compact.join(' ')
  end

end

app/models/video.rb
class Video < ApplicationRecord

	include ImageUploader::Attachment.new(:image)
	
end

app/controllers/tipus_dada_inventaris_controller.rb
class TipusDadaInventarisController < ApplicationController
  before_action :set_tipus_dada_inventari, only: [:show, :edit, :update, :destroy]

  # GET /tipus_dada_inventaris
  # GET /tipus_dada_inventaris.json
  def index
    @tipus_dada_inventaris = TipusDadaInventari.all
  end

  # GET /tipus_dada_inventaris/1
  # GET /tipus_dada_inventaris/1.json
  def show
  end

  # GET /tipus_dada_inventaris/new
  def new
    @tipus_dada_inventari = TipusDadaInventari.new
  end

  # GET /tipus_dada_inventaris/1/edit
  def edit
  end

  # POST /tipus_dada_inventaris
  # POST /tipus_dada_inventaris.json
  def create
    @tipus_dada_inventari = TipusDadaInventari.new(tipus_dada_inventari_params)

    respond_to do |format|
      if @tipus_dada_inventari.save
        format.html { redirect_to @tipus_dada_inventari, notice: 'Tipus dada inventari was successfully created.' }
        format.json { render :show, status: :created, location: @tipus_dada_inventari }
      else
        format.html { render :new }
        format.json { render json: @tipus_dada_inventari.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipus_dada_inventaris/1
  # PATCH/PUT /tipus_dada_inventaris/1.json
  def update
    respond_to do |format|
      if @tipus_dada_inventari.update(tipus_dada_inventari_params)
        format.html { redirect_to @tipus_dada_inventari, notice: 'Tipus dada inventari was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipus_dada_inventari }
      else
        format.html { render :edit }
        format.json { render json: @tipus_dada_inventari.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipus_dada_inventaris/1
  # DELETE /tipus_dada_inventaris/1.json
  def destroy
    @tipus_dada_inventari.destroy
    respond_to do |format|
      format.html { redirect_to tipus_dada_inventaris_url, notice: 'Tipus dada inventari was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipus_dada_inventari
      @tipus_dada_inventari = TipusDadaInventari.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipus_dada_inventari_params
      params.require(:tipus_dada_inventari).permit(:nom_ca, :nom_es, :nom_en, :unitats)
    end
end

app/helpers/dapcons_helper.rb
module DapconsHelper
end

app/helpers/foto_casos_helper.rb
module FotoCasosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/noticies_helper.rb
module NoticiesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/productes_helper.rb
module ProductesHelper
end

app/helpers/tipus_dada_inventaris_helper.rb
module TipusDadaInventarisHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/tipus_dada_inventaris/_form.html.erb
<%= simple_form_for(@tipus_dada_inventari) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nom_ca %>
    <%= f.input :nom_es %>
    <%= f.input :nom_en %>
    <%= f.input :unitats %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tipus_dada_inventaris/edit.html.erb
<h1>Editing Tipus Dada Inventari</h1>

<%= render 'form', tipus_dada_inventari: @tipus_dada_inventari %>

<%= link_to 'Show', @tipus_dada_inventari %> |
<%= link_to 'Back', tipus_dada_inventaris_path %>

app/views/tipus_dada_inventaris/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipus Dada Inventaris</h1>

<table>
  <thead>
    <tr>
      <th>Nom ca</th>
      <th>Nom es</th>
      <th>Nom en</th>
      <th>Unitats</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipus_dada_inventaris.each do |tipus_dada_inventari| %>
      <tr>
        <td><%= tipus_dada_inventari.nom_ca %></td>
        <td><%= tipus_dada_inventari.nom_es %></td>
        <td><%= tipus_dada_inventari.nom_en %></td>
        <td><%= tipus_dada_inventari.unitats %></td>
        <td><%= link_to 'Show', tipus_dada_inventari %></td>
        <td><%= link_to 'Edit', edit_tipus_dada_inventari_path(tipus_dada_inventari) %></td>
        <td><%= link_to 'Destroy', tipus_dada_inventari, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipus Dada Inventari', new_tipus_dada_inventari_path %>

app/views/tipus_dada_inventaris/new.html.erb
<h1>New Tipus Dada Inventari</h1>

<%= render 'form', tipus_dada_inventari: @tipus_dada_inventari %>

<%= link_to 'Back', tipus_dada_inventaris_path %>

app/views/tipus_dada_inventaris/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom ca:</strong>
  <%= @tipus_dada_inventari.nom_ca %>
</p>

<p>
  <strong>Nom es:</strong>
  <%= @tipus_dada_inventari.nom_es %>
</p>

<p>
  <strong>Nom en:</strong>
  <%= @tipus_dada_inventari.nom_en %>
</p>

<p>
  <strong>Unitats:</strong>
  <%= @tipus_dada_inventari.unitats %>
</p>

<%= link_to 'Edit', edit_tipus_dada_inventari_path(@tipus_dada_inventari) %> |
<%= link_to 'Back', tipus_dada_inventaris_path %>