config/routes.rb
Rails.application.routes.draw do
  resources :indicadors
  resources :tipus_indicadors
  resources :tipus_dada_inventaris
  resources :producte_dapcons
  resources :cerca_productes
  get 'productes/cerca_productes'
  get 'dapcons', to: 'dapcons#index', :as => :dapcons
  get 'dapcons/que_son'
  get 'dapcons/utilitat'
  get 'dapcons/organitzacions_afiliades'
  get 'dapcons/productes_registrats'
  get 'dapcons/empreses_dapcons'
  get 'dapcons/documents_oficials'
  get 'dapcons/administradors'
  get 'dapcons/consell_assessor'
  get 'dapcons/panells_sectorials'
  get 'dapcons/eco_platform'
  get 'dapcons/entitats_colaboradores'
  get 'dapcons/verificadors'
  get 'dapcons/afiliacio'
  get 'dapcons/registrar_producte'
  get 'dapcons/contacte'
  get 'dapcons/comparador'
  resources :foto_casos
  resources :photos
  get 'temes_clau/index'
  get 'temes_clau/marc_conceptual'
  get 'temes_clau/materials'
  get 'temes_clau/energia_passius'
  get 'temes_clau/energia_actius'
  get 'temes_clau/energia_renovables'
  get 'temes_clau/aigua'
  get 'temes_clau/residus'
  get 'temes_clau/salut'
  get 'videos/llistat'
  get 'cas_practics/llistat'
  get 'productes/llistat'

  resources :videos
  resources :productes
  resources :cas_practics
  resources :noticies
  devise_for :users
  get 'home/index'
  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :update, Noticia do |noticia|
        noticia.user == user
      end
      can :destroy, Noticia do |noticia|
        noticia.user == user
      end
      can :create, Noticia
      can :read, :all
    end  
  end
end

app/models/cas_practic.rb
class CasPractic < ApplicationRecord

	has_many :foto_casos

end

app/models/cerca_producte.rb
class CercaProducte < ApplicationRecord
end

app/models/foto_cas.rb
class FotoCas < ApplicationRecord
	include ImageUploader[:image]

	belongs_to :cas_practic
end

app/models/image_uploader.rb
class ImageUploader < Shrine
	require "image_processing/mini_magick"
	include ImageProcessing::MiniMagick
  plugin :processing
  plugin :versions

	Attacher.validate do
    validate_max_size 2.megabyte, message: "is too large (max is 2 MB)"
    validate_mime_type_inclusion ['image/jpg', 'image/jpeg', 'image/png']
	end

	plugin :determine_mime_type
	plugin :cached_attachment_data
	plugin :remove_attachment
	plugin :delete_raw
	plugin :store_dimensions

	process(:store) do |io, context|
    { original: io, medium: resize_to_fit!(io.download, 600, 600), thumb: resize_to_limit!(io.download, 300, 300) }
  end
end

app/models/indicador.rb
class Indicador < ApplicationRecord

	belongs_to :producte_dapcons

end

app/models/noticia.rb
class Noticia < ApplicationRecord

	include ImageUploader::Attachment.new(:image)

end

app/models/photo.rb
class Photo < ApplicationRecord
	include ImageUploader[:image]
end

app/models/producte.rb
class Producte < ApplicationRecord
end

app/models/producte_dapcons.rb
class ProducteDapcons < ApplicationRecord

	has_many :indicadors

end

app/models/tipus_indicador.rb
class TipusIndicador < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name
    [first_name, last_name].compact.join(' ')
  end

end

app/models/video.rb
class Video < ApplicationRecord

	include ImageUploader::Attachment.new(:image)
	
end

app/controllers/producte_dapcons_controller.rb
class ProducteDapconsController < ApplicationController
  before_action :set_producte_dapcons, only: [:show, :edit, :update, :destroy]

  # GET /producte_dapcons
  # GET /producte_dapcons.json
  def index
    @producte_dapcons = ProducteDapcons.all
  end

  # GET /producte_dapcons/1
  # GET /producte_dapcons/1.json
  def show
  end

  # GET /producte_dapcons/new
  def new
    @producte_dapcons = ProducteDapcons.new
  end

  # GET /producte_dapcons/1/edit
  def edit
  end

  # POST /producte_dapcons
  # POST /producte_dapcons.json
  def create
    @producte_dapcons = ProducteDapcons.new(producte_dapcons_params)

    respond_to do |format|
      if @producte_dapcons.save
        format.html { redirect_to @producte_dapcons, notice: 'Producte dapcons was successfully created.' }
        format.json { render :show, status: :created, location: @producte_dapcons }
      else
        format.html { render :new }
        format.json { render json: @producte_dapcons.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /producte_dapcons/1
  # PATCH/PUT /producte_dapcons/1.json
  def update
    respond_to do |format|
      if @producte_dapcons.update(producte_dapcons_params)
        format.html { redirect_to @producte_dapcons, notice: 'Producte dapcons was successfully updated.' }
        format.json { render :show, status: :ok, location: @producte_dapcons }
      else
        format.html { render :edit }
        format.json { render json: @producte_dapcons.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /producte_dapcons/1
  # DELETE /producte_dapcons/1.json
  def destroy
    @producte_dapcons.destroy
    respond_to do |format|
      format.html { redirect_to producte_dapcons_index_url, notice: 'Producte dapcons was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producte_dapcons
      @producte_dapcons = ProducteDapcons.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def producte_dapcons_params
      params.require(:producte_dapcons).permit(:nom_ca, :nom_es, :nom_en, :descripcio_ca, :descripcio_es, :descripcio_en, :identificador, :rcp_ca, :rcp_es, :rcp_en, :validesa_inici, :validesa_fi, :empresa, :categoria_indicadors)
    end
end

app/helpers/dapcons_helper.rb
module DapconsHelper
end

app/helpers/foto_casos_helper.rb
module FotoCasosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/indicadors_helper.rb
module IndicadorsHelper
end

app/helpers/noticies_helper.rb
module NoticiesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/producte_dapcons_helper.rb
module ProducteDapconsHelper
end

app/helpers/productes_helper.rb
module ProductesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/producte_dapcons/_form.html.erb
<%= simple_form_for(@producte_dapcons) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nom_ca %>
    <%= f.input :nom_es %>
    <%= f.input :nom_en %>
    <%= f.input :descripcio_ca %>
    <%= f.input :descripcio_es %>
    <%= f.input :descripcio_en %>
    <%= f.input :identificador %>
    <%= f.input :rcp_ca %>
    <%= f.input :rcp_es %>
    <%= f.input :rcp_en %>
    <%= f.input :validesa_inici %>
    <%= f.input :validesa_fi %>
    <%= f.input :empresa %>
    <%= f.input :categoria_indicadors %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/producte_dapcons/edit.html.erb
<h1>Editing Producte Dapcons</h1>

<%= render 'form', producte_dapcons: @producte_dapcons %>

<%= link_to 'Show', @producte_dapcons %> |
<%= link_to 'Back', producte_dapcons_index_path %>

app/views/producte_dapcons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Producte Dapcons</h1>

<table>
  <thead>
    <tr>
      <th>Nom ca</th>
      <th>Nom es</th>
      <th>Nom en</th>
      <th>Descripcio ca</th>
      <th>Descripcio es</th>
      <th>Descripcio en</th>
      <th>Identificador</th>
      <th>Rcp ca</th>
      <th>Rcp es</th>
      <th>Rcp en</th>
      <th>Validesa inici</th>
      <th>Validesa fi</th>
      <th>Empresa</th>
      <th>Categoria indicadors</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @producte_dapcons.each do |producte_dapcons| %>
      <tr>
        <td><%= producte_dapcons.nom_ca %></td>
        <td><%= producte_dapcons.nom_es %></td>
        <td><%= producte_dapcons.nom_en %></td>
        <td><%= producte_dapcons.descripcio_ca %></td>
        <td><%= producte_dapcons.descripcio_es %></td>
        <td><%= producte_dapcons.descripcio_en %></td>
        <td><%= producte_dapcons.identificador %></td>
        <td><%= producte_dapcons.rcp_ca %></td>
        <td><%= producte_dapcons.rcp_es %></td>
        <td><%= producte_dapcons.rcp_en %></td>
        <td><%= producte_dapcons.validesa_inici %></td>
        <td><%= producte_dapcons.validesa_fi %></td>
        <td><%= producte_dapcons.empresa %></td>
        <td><%= producte_dapcons.categoria_indicadors %></td>
        <td><%= link_to 'Show', producte_dapcons %></td>
        <td><%= link_to 'Edit', edit_producte_dapcons_path(producte_dapcons) %></td>
        <td><%= link_to 'Destroy', producte_dapcons, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Producte Dapcons', new_producte_dapcons_path %>

app/views/producte_dapcons/new.html.erb
<h1>New Producte Dapcons</h1>

<%= render 'form', producte_dapcons: @producte_dapcons %>

<%= link_to 'Back', producte_dapcons_index_path %>

app/views/producte_dapcons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom ca:</strong>
  <%= @producte_dapcons.nom_ca %>
</p>

<p>
  <strong>Nom es:</strong>
  <%= @producte_dapcons.nom_es %>
</p>

<p>
  <strong>Nom en:</strong>
  <%= @producte_dapcons.nom_en %>
</p>

<p>
  <strong>Descripcio ca:</strong>
  <%= @producte_dapcons.descripcio_ca %>
</p>

<p>
  <strong>Descripcio es:</strong>
  <%= @producte_dapcons.descripcio_es %>
</p>

<p>
  <strong>Descripcio en:</strong>
  <%= @producte_dapcons.descripcio_en %>
</p>

<p>
  <strong>Identificador:</strong>
  <%= @producte_dapcons.identificador %>
</p>

<p>
  <strong>Rcp ca:</strong>
  <%= @producte_dapcons.rcp_ca %>
</p>

<p>
  <strong>Rcp es:</strong>
  <%= @producte_dapcons.rcp_es %>
</p>

<p>
  <strong>Rcp en:</strong>
  <%= @producte_dapcons.rcp_en %>
</p>

<p>
  <strong>Validesa inici:</strong>
  <%= @producte_dapcons.validesa_inici %>
</p>

<p>
  <strong>Validesa fi:</strong>
  <%= @producte_dapcons.validesa_fi %>
</p>

<p>
  <strong>Empresa:</strong>
  <%= @producte_dapcons.empresa %>
</p>

<p>
  <strong>Categoria indicadors:</strong>
  <%= @producte_dapcons.categoria_indicadors %>
</p>

<%= link_to 'Edit', edit_producte_dapcons_path(@producte_dapcons) %> |
<%= link_to 'Back', producte_dapcons_index_path %>